#!/bin/bash
## Load slug from Bind Mount, URL or STDIN

set -x
set -eo pipefail

export HOME=/app
mkdir -p "${HOME}"
cd $HOME

## Load profile.d and release config
shopt -s nullglob
mkdir -p .profile.d
if [[ -s .release ]]; then
  ruby -r yaml > .profile.d/config_vars <<-RUBY
release = YAML.load_file('.release') || {}
config = release['config_vars'] || {}
config.each_pair do |k, v|
  puts "#{k}=\${#{k}:-'#{v}'}"
end
RUBY
fi
for file in .profile.d/*; do
  . "${file}"
done
hash -r

## Inject "start" command to run processes defined in Procfile
case "$1" in
  start)
    if [[ -f Procfile ]]; then
      command=$(ruby -r yaml -e "puts YAML.load_file('Procfile')['$2']")
    elif [[ -f .release ]]; then
      command=$(ruby -r yaml -e "puts (YAML.load_file('.release') || {}).fetch('default_process_types', {})['$2']")
    else
      echo "file: [Procfile] or [.release] required for command start"
      exit 1
    fi
    ;;
  *)
    printf -v command " %q" "$@"
    ;;
esac

## Run!
if [ "$command" == " ''" ]; then
	echo -e "empty startup command"
	exit 1
fi
echo -e "startup command: $command"
exec bash -c "${command}"
